#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_SEARCH_DIALOG                       101
#define IDI_DLL                                 103
#define IDI_CUR_BUSY_SEARCH                     105
#define IDI_CUR_BUSY_EXTRACT                    106
#define IDI_FOLDER                              108
#define IDD_ABOUT                               110
#define IDC_CBX_MASK                            1002
#define IDC_RBTN_CURRENT_FILE                   1004
#define IDC_STATIC_1                            1016
#define IDC_BTN_BROWSE_BASE_PATH                1018
#define IDC_STATIC_2                            1019
#define IDC_RBTN_EXTRACT_EACH_MATCH             1033
#define IDC_RBTN_EXTRACT_SINGLE_FILE            1034
#define IDC_RBTN_WITH_SEPARATOR                 1035
#define IDC_RBTN_PRETTY_PRINT                   1036
#define IDC_EDIT_SEPARATOR                      1037
#define IDC_CHK_ADD_HEADER                      1038
#define IDC_RBTN_EXTRACT_WITH_REPLACE           1039
#define IDC_RBTN_EXTRACT_TO_NPP                 1040
#define IDC_RBTN_SAVE_AS_NEW_FILES              1041
#define IDC_CHK_OPEN_FILES_IN_NPP               1044
#define IDC_RBTN_NO_CONVERSION                  1045
#define IDC_RBTN_ALL_UPPERCASE                  1046
#define IDC_RBTN_ALL_LOWERCASE                  1047
#define IDC_RBTN_FIRST_UPPERCASE                1048
#define IDC_CHK_SKIP_WHOLE_MATCH                1049
#define IDC_RBTN_NO_SORT                        1050
#define IDC_RBTN_SORT_ASCENDING                 1051
#define IDC_RBTN_SORT_DESCENDING                1052
#define IDC_CHK_FILTER_UNIQUE                   1053
#define IDC_CHK_CASE_INSENSITIVE                1054
#define IDC_CHK_DOT_MATCH_NEW_LINES             1055
#define IDC_BTN_SEARCH                          1056
#define IDC_BTN_EXTRACT                         1057
#define IDC_EDIT_TEMPALTE_NAME                  1062
#define IDC_CBX_FIND                            1063
#define IDC_CBX_REPLACE                         1064
#define IDC_CBX_BASE_PATH                       1065
#define IDC_RBTN_ALL_OPENED_FILES               1067
#define IDC_RBTN_ALL_FROM_LOCATION              1068
#define IDC_CHK_FROM_SELECTION                  1069
#define IDC_CBX_PATH                            1070
#define IDC_BTN_FOLDER                          40000
#define ID_BUILD_DATE                           40001
#define ID_COMPILER                             40002
